ALTER TABLE PUBLIC.USERDATA ADD CITY VARCHAR(255);
ALTER TABLE PUBLIC.USERDATA ADD STREET VARCHAR(255);
ALTER TABLE PUBLIC.USERDATA ADD HOUSENUMBER INTEGER;
ALTER TABLE PUBLIC.USERDATA ADD COUNTRY VARCHAR(255);