INSERT INTO PUBLIC.USERDATA (NAME, HEIGHT, DATE_OF_BIRTH, CITY, STREET, HOUSENUMBER, COUNTRY)
VALUES ('Karkinkar', 179, '1988-05-23', 'New Delhi', 'Pusa Road', '165', 'India');

INSERT INTO PUBLIC.USERDATA (NAME, HEIGHT, DATE_OF_BIRTH, CITY, STREET, HOUSENUMBER, COUNTRY)
VALUES ('GEETIKA', 172, '1989-04-08', 'Tirupathi', 'Ram Road', '195', 'India');

INSERT INTO PUBLIC.USERDATA (NAME, HEIGHT, DATE_OF_BIRTH, CITY, STREET, HOUSENUMBER, COUNTRY)
VALUES ('SRINIVAS', 179, '1990-07-25', 'New Delhi', 'Pusa Road', '167', 'India');